### ISSUE TITLE
Error during executing stepMIV function

### ISSUE THREAD

**Issue by jyk** [andrija-djurovic/PDtoolkit#1]
Hi.
I got next error after executing the stepMIV while following example (I have executed all preceding commands in the example https://github.com/andrija-djurovic/PDtoolkit#readme) : 
> multiv.res <- stepMIV(start.model = Creditability ~ 1, 
                       miv.threshold = 0.02, 
                       m.ch.p.val = 0.05,
                       coding = "WoE",
                       db = loans)
[1] "Running iteration: 1"
Error in model.frame.default(formula = model.formula, data = db, offset = offset,  : 
  invalid type (closure) for variable '(offset)'

**Comment by andrija-djurovic** [comment]
Hi. 
I've been updating stepMIV function in last few days, so you probably didn't install the latest version.  The checks I performed now were ok.

Please, try to install it again and let me know if it works:
devtools::install_github("andrija-djurovic/PDtoolkit")

Andrija

**Comment by jyk** [comment]
Thanks, now I am fine :)
