### ISSUE TITLE
PSI binning

### ISSUE THREAD

**Issue by michaelalex2** [andrija-djurovic/PDtoolkit#2]
Hi, as far as I understand it the bins in PSI should be found from the quantiles of the base distribution, rather than cutting the base distribution into equal width bins which I believe is currently what the num.bt() helper function for psi() is doing?

**Comment by andrija-djurovic** [comment]
Hi,

I am not aware of any strict rule for discretizing numeric variables for this purpose. 
My choice was motivated by the fact that, in credit risk modeling, we refer to equal-width binning as the "naive" binning approach. Additionally, this method preserves the shape of the original variable distribution. 

To exemplify this, please consider the following example and note the difference in the distribution shape of these two methods:

```{r}
set.seed(1)
#simulate x from the standard normal distribution
x <- rnorm(1e4)
# Select the number of bins
bin <- 10
#binning based on quantiles
probs <- seq(from = 0, to = 1, length.out = bin + 1) 
b.qu <- quantile(x = x, probs = probs)
x.qu <- cut(x = x, 
            breaks = b.qu,
            include.lowest = TRUE, 
            labels = FALSE, 
            right = FALSE)
#binning based on equal-width intervals
x.ew <- cut(x = x, 
            breaks = bin,
            include.lowest = TRUE, 
            labels = FALSE, 
            right = FALSE)
#comparison of two binning methods
par(mfrow = c(3, 1))
hist(x, main = "Histogram of the original x")
barplot(table(x.qu), main = "Barplot quantiles")
barplot(table(x.ew), main = "Barplot equal width")
```

To conclude, I would not consider this an issue of the ```psi``` function. 
Nevertheless, if, for your use case, you find binning based on the quantiles more appropriate, you can easily change it within the source code of the ```num.bt``` helper function.
