### ISSUE TITLE
Add two-tailed test for function pp.testing

### ISSUE THREAD

**Issue by jyrkuusik** [andrija-djurovic/PDtoolkit#3]
This is not an issue, but missing of functionality:
Currently function pp.testing implements one-sided test only.
Please add two-sided test option as well:
binomial.res.two.sided, jeffreys.res.two.sided, zscore.res.two.sided, hosmer.lemeshow.res.two.sided:
H0: ODR = PDC (H1: ODR < PDC or H1: ODR > PDC)

**Comment by andrija-djurovic** [comment]
Unfortunately, I will not be implementing these changes. The primary reason is that there is no natural and simple way to introduce a two-sided version for some of the tests used in predictive power testing. Specifically, there is no straightforward way to do this for Jeffrey's test and the binomial test. Additionally, the most common hypothesis for predictive power is that the calibrated PD is not underestimated, so the existing tests serve their purpose.

However, for those interested in a two-sided version of predictive power testing, the z-score test can be used independently by adjusting the code provided below. A simpler alternative is to use R's built-in function `prop.test`, which serves the same purpose and allows selection of the appropriate test version using the `alternative` argument.

Given the above reasons, I will consider this issue/task closed and completed.

```
#z-score test:
zscore.test <- function(pdc, odr, no) {
	se <-  sqrt((pdc * (1 - pdc)) / no)
	test.stat <- (odr - pdc) / se
	p.val <- pnorm(test.stat, lower.tail = FALSE)
return(p.val)
}
```
